INSERT INTO CURRENCIES(NAME,CODE,SYMBOL) VALUES('Peso','ARS','$');
INSERT INTO CURRENCIES(NAME,CODE,SYMBOL) VALUES('Dollar','USD','$');
INSERT INTO CURRENCIES(NAME,CODE,SYMBOL) VALUES('Euro','EU','€');

INSERT INTO MARKETS(NAME,CODE,CURRENCY_ID) VALUES('Argentina','ARG',1);

INSERT INTO CURRENCY_VALUES(REGISTERED_AT,PURCHASE_VALUE,SALE_VALUE,IS_ACTIVE,CURRENCY_ID,MARKET_ID)
VALUES('2022-12-1',355,360,false,2,1);
INSERT INTO CURRENCY_VALUES(REGISTERED_AT,PURCHASE_VALUE,SALE_VALUE,IS_ACTIVE,CURRENCY_ID,MARKET_ID)
VALUES('2023-1-1',365,370,false,2,1);
INSERT INTO CURRENCY_VALUES(REGISTERED_AT,PURCHASE_VALUE,SALE_VALUE,IS_ACTIVE,CURRENCY_ID,MARKET_ID)
VALUES('2023-2-1',375,380,true,2,1);
INSERT INTO CURRENCY_VALUES(REGISTERED_AT,PURCHASE_VALUE,SALE_VALUE,IS_ACTIVE,CURRENCY_ID,MARKET_ID)
VALUES('2023-1-1',390,395,false,3,1);
INSERT INTO CURRENCY_VALUES(REGISTERED_AT,PURCHASE_VALUE,SALE_VALUE,IS_ACTIVE,CURRENCY_ID,MARKET_ID)
VALUES('2023-2-1',400,405,true,3,1);

INSERT INTO USERS(USERNAME,PASSWORD,ROLE) VALUES('user','$2a$10$EY9KjdLeiJBlJcxEnhO9.e4m5csrD7TDgKFFyELGQuP494R6e0osG','USER');
INSERT INTO USERS(USERNAME,PASSWORD,ROLE) VALUES('admin','$2a$10$EY9KjdLeiJBlJcxEnhO9.e4m5csrD7TDgKFFyELGQuP494R6e0osG','ADMIN');