DROP TABLE IF EXISTS CURRENCIES;
CREATE TABLE CURRENCIES(
ID BIGINT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
CODE VARCHAR(10) NOT NULL,
SYMBOL VARCHAR(10) NOT NULL,
PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS MARKETS;
CREATE TABLE MARKETS(
ID BIGINT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
CODE VARCHAR(10) NOT NULL,
CURRENCY_ID BIGINT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(CURRENCY_ID) REFERENCES CURRENCIES(ID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS CURRENCY_VALUES;
CREATE TABLE CURRENCY_VALUES(
ID BIGINT NOT NULL AUTO_INCREMENT,
REGISTERED_AT DATE NOT NULL,
PURCHASE_VALUE DECIMAL(14,4) NOT NULL,
SALE_VALUE DECIMAL(14,4) NOT NULL,
IS_ACTIVE BOOLEAN NOT NULL,
CURRENCY_ID BIGINT NOT NULL,
MARKET_ID BIGINT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(CURRENCY_ID) REFERENCES CURRENCIES(ID) ON DELETE CASCADE,
FOREIGN KEY(MARKET_ID) REFERENCES MARKETS(ID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
ID BIGINT NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
ROLE ENUM('USER','ADMIN') NOT NULL
);